### ISSUE TITLE
TextOneLine changes height

### ISSUE THREAD

**Issue by smakarov** [marcglasberg/assorted_layout_widgets#19]
Hi there! I have 1 line text and it shows height 18 in the inspector and with your TextOneLine it becomes 27, which breaks layout.

**Comment by marcglasberg** [comment]
The `Textfield` widget itself has bugs (for example, see: https://github.com/flutter/flutter/issues/59719) so the only way for me to see if it's a bug in `Textfield` or `TextOneLine`, or some other problem, is for you to show me some code that demonstrates the problem you are having.

Can you provide me with a very simple, runnable code (with main method and all) that demonstrates the problem you are having? If you can do that I will have a look at it right away.

**Comment by smakarov** [comment]
@marcglasberg Here the test project(1.5 mb), please follow TODO marks
https://disk.yandex.ru/d/WTIrpKHPP9BuBA
I found that there is problem with Comfortaa font. With other project font(Circle) it works fine.

**Comment by marcglasberg** [comment]
Hi, I actually would need a very simple, single file, example, with as little lines as possible. Something with, say, 20 lines. I can't use a 1.5 mb project.

If you see the `TextOneLine` code, it's extremely simple, it just calls a Text:

```
class TextOneLine extends Text {
  const TextOneLine(
    String data, {
    ...
  }) : super(
          data,
          ...
          maxLines: 1,
        );

  @override
  String? get data => super.data == null ? null : Characters(super.data!).toList().join("\u{200B}");
}
```

The only significant difference that could impact the height, maybe, is `maxLines: 1`. I can't actually remove that, so if the `Text` is changing height when you force it to be 1 line, I can't do much to fix it.

Instead of using `TextOneLine` try using a `Text` with `maxLines: 1` and see if it also becomes height 27 pixels. If it does, and if you fell that's a bug, please open an issue in the flutter GitHub repo.

**Comment by smakarov** [comment]
Comment/uncomment "maxLines: 1" line does not impact on regular Text widget(height 18 in both cases).

**Comment by marcglasberg** [comment]
Ok, the other difference is that the String you are using as data gets transformed like this:

`Characters(super.data!).toList().join("\u{200B}")`

So, could you please try your Text widget like this?

`Text(Characters("Abcd").toList().join("\u{200B}"), style: ...)`

The char `\u{200B}` above is a "Zero Width Space". Maybe in that font you are using this char actually occupies some height...

**Comment by smakarov** [comment]
You are right. So is it font issue or Text components that draw this font?

**Comment by marcglasberg** [comment]
I'd say that's a font issue. Ideally a zero-width-space should have no height. Also, ideally the `TextOneLine` should not break if a zero-width-space has height. But that's how it's implemented, and I can't fix that. So I suggest you use another font, if possible.
