### ISSUE TITLE
Is there something like flexShrink in css?

### ISSUE THREAD

**Issue by danielchan303** [marcglasberg/assorted_layout_widgets#23]
I have a row with text on the left and some icons on the right. I want the icon to be just next to the text all the time.

The Row will push the icons away if the text is too long, and the RowSuper that you created will shrink the icons if there is not enough space. 

Is there something like flex_shrink in your library to allow a widget (the text in my case) to expand only if the row overflow?

**Comment by marcglasberg** [comment]
I am not sure I understood exactly what you want, but maybe it's another widget from this package, called SideBySide. Have a look:

# SideBySide 

The SideBySide widget disposes 2 widgets horizontally, while achieving a layout which is impossible for both the native Row and the RowSuper widgets.

The startChild will be on the left, and will occupy as much space as it wants, up to the available horizontal space.

The endChild will be on the right of the startChild widget, and it will occupy the rest of the available space. Note: This means, if the startChild widget occupies all the available space, then endChild widget will not be displayed (since it will be sized as 0 width).

For example, suppose you want to create a title with a divider that occupies the rest of the space:

```
return SideBySide(
  startChild: Text("First Chapter", textWidthBasis: TextWidthBasis.longestLine),
  endChild: Divider(color: Colors.grey),
  innerDistance: 8,
  minEndChildWidth: 20,
);
```
