### ISSUE TITLE
TextOneLine: Letterspacing rendered different 

### ISSUE THREAD

**Issue by AFAS-HHO** [marcglasberg/assorted_layout_widgets#26]
![image](https://user-images.githubusercontent.com/52655616/225865150-37d1d4b5-8810-40ad-9e0e-f633e647e208.png)

Code to reproduce (assuming usage of GoogleFonts package)
```dart
 final TextStyle style = GoogleFonts.inter(
      fontSize: 10,
      fontWeight: FontWeight.w500,
      letterSpacing: 1.1,
    );
    const String textValue =
        'Consectetur adipiscing elit. Et sept en andor cras massa mass';

    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          TextOneLine(
            textValue,
            style: style,
          ),
          const SizedBox(height: 4.0),
          Text(
            textValue,
            style: style,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
    );`
```

TextOneLine seems to render extra letter spacing, This is also the case with a default letter spacing, giving it a higher value seems to make the difference even greater.

**Comment by AFAS-HHO** [comment]
After further looking into it it seems that that Zero-width space still applies letter spacing.

My suggestion is to apply on the textStyle with a letterSpacingFactor of 0.5

```dart
.apply(
    letterSpacingFactor: 0.5
);
```

**Comment by marcglasberg** [comment]
I've never used letterSpacing, so I've never experienced this. Clearly, `TextOneLine` is incompatible with letterSpacing. I believe `.apply(letterSpacingFactor: 0.5);` should solve it, unless this introduces some other problem I can't see right now. I will apply this fix.

The `TextOneLine` widget was never supposed to exist for that long, it was just a temporary fix for the wrapping problem. Hope they fix that one day so that I can deprecate this widget.
